[window]
opacity = 0.9
padding = { x = 10, y = 10}
decorations_theme_variant = "Dark"

[font]
normal = { family = "JetBrains Mono", style = "Regular" } 
size = 12

[hints]
alphabet = "<string>"


[bell]
animation = "EaseOutExpo"



[cursor]
style = { shape = "Beam", blinking = "On" }
